package ch.cyril.budget.manager.backend.service.mongo

const val KEY_ID = "_id"
const val KEY_NAME = "name"
const val KEY_CATEGORY = "category"
const val KEY_DATE = "date"
const val KEY_METHOD = "method"
const val KEY_AUTHOR = "author"
const val KEY_TAGS = "tags"
const val KEY_AMOUNT = "amount"
const val KEY_PERIOD = "period"
const val KEY_FROM = "from"
const val KEY_TO = "to"
const val KEY_WEEKLY = "weekly"
const val KEY_MONTHLY = "monthly"
const val KEY_LAST_UPDATE = "lastUpdate"